### ISSUE TITLE
Error Cell_VAE.py

### ISSUE THREAD

**Issue by a-miyaki** [a-miyaki/vae#6]
From Cell_VAE.py

> def test(epoch):
    model.eval()
    test_loss = 0
    for batch_idx, (data, _) in enumerate(testdata_loader):
        data = data.to(device)
        recon_batch, mu, logvar = model(data)
        test_loss += loss_function(recon_batch, data, mu, logvar).item()
        """
        if epoch % 10 == 0:
            # 10エポックごとに最初のminibatchの入力画像と復元画像を保存
            if batch_idx == 0:
                n = 8
                comparison = torch.cat([data[:n], recon_batch.view(args.batch_size, 1, 28, 28)[:n]])
                save_image(comparison.data.cpu(),
                           '{}/reconstruction_{}.png'.format(args.out, epoch), nrow=n)
        """
    test_loss /= len(testdata_loader.dataset)

Error in """ ~~ """.
args.batch_size = 128
input image = ((28, 28)) Gray scale
Why do it occur this error?

**Comment by a-miyaki** [comment]
#error message
`Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.6\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.6\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.6\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.6\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/mizukami-lab/PycharmProjects/miyaki/cell_VAE.py", line 147, in <module>
    test_loss = test(epoch)
  File "C:/Users/mizukami-lab/PycharmProjects/miyaki/cell_VAE.py", line 133, in test
    comparison = torch.cat([data[:n], recon_batch.view(args.batch_size, 1, 28, 28)[:n]])
RuntimeError: shape '[128, 1, 28, 28]' is invalid for input of size 301056`

**Comment by a-miyaki** [comment]
It is settled.
I think to read image for Gray Scale, but in fact, images read for color.
I add transforms.Grayscale.
